### ISSUE TITLE
[Feature] 希望增加根据SSID切换出站模式的功能，家里有软路由，希望回家自动切直连，出门切规则！

### ISSUE THREAD

**Issue by imfeisir** [chen08209/FlClash#1118]
### 功能描述 / Feature description

之前一直使用iOS上的Quantumult X，家里有软路由，根据WiFi自动切换直连和规则模式是刚需！
现在换了安卓手机，一直没遇到有支持该功能的，请问大佬这个容易实现么在安卓设备上？
经常在外面的时候忘记开，收不到Telegram推送和Gmail邮件。很难受。

### 使用场景 / Use case

回家连上设置的WiFi名，自动切换成直连模式，出门断开WiFi后自动切换成规则模式！

### 适用系统 / Target OS

- [x] Android
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Comment by bettworks** [comment]
你这个问题，mihomo内核目前没有这个功能，Singbox有相关配置可以看下文档，APP的话冲浪板有类似功能（可用surge配置实现）

**Comment by zakizou** [comment]
圈这个功能好用

**Comment by bettworks** [comment]
> 圈这个功能好用

人说的是安卓

**Comment by lu5je0** [comment]
赞同

**Comment by Tommytalk** [comment]
mihomo party 有。

**Comment by bettworks** [comment]
> mihomo party 有。

这个规则在移动端比较有用，PC端意义不大

**Comment by deceiver404** [comment]
给mac和android加上了基于ssid 和 wifi ip的策略，如果基于ssid 需要位置权限，如果基于ip不需要(推荐)

https://github.com/deceiver404/FlMihomo

WiFi ssid policy

```yaml
proxy-groups:
  - name: "🚀 节点选择"
    type: select
    proxies: [...]
    ssid-policy:
      "ip:192.168.10.": "home"       # 匹配 192.168.10.x（家里）
      "ip:10.10.": "office"        # 匹配 10.10.x.x（公司）
      "HomeWiFi": "DIRECT"         # SSID
      "cellular": "hk"          # 移动网络
      "default": "auto"            # 默认规则
```
