### ISSUE TITLE
[BUG] 自定义groups安卓端无法显示，其他客户端未测试

### ISSUE THREAD

**Issue by lpdswing** [chen08209/FlClash#1224]
### 问题描述 / Describe the bug
```
proxy-groups:
  - name: 回家
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Back.png
    type: select
    proxies:
      - 回家节点
      - DIRECT
  - name: 回家节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Back.png
    include-all: true
    filter: (?i)wg
    type: url-test
    interval: 300
    tolerance: 50
rule-providers:
  GOHOME:
    url: https://testingcf.jsdelivr.net/gh/lpdswing/mihomo-providers@main/home.list
    path: ./ruleset/home.list
    behavior: classical
    interval: 86400
    format: text
    type: http
rules:
  - RULE-SET,GOHOME,回家
```

添加以上自定义配置，代理组无法展示，其他自动选择，手动选择，电报消息，苹果服务等代理组正常显示，实测功能正常，就是无法显示进行回家组的节点选择。

### 软件版本 / Version

0.8.85

### 复现步骤 / To Reproduce

把描述中的配置项添加测试

### 操作系统 / OS

Android

### 操作系统版本 / OS Version

鸿蒙4.2

### 日志(勿上传日志文件，请粘贴日志内容) / Log (Do not upload the log file, paste the log content directly)

无
