### ISSUE TITLE
无法进行分流

### ISSUE THREAD

**Issue by jenfonro** [chen08209/FlClash#1242]
规则配置如下：
```
rule-providers:
  Youtube:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
    path: ./ruleset/Youtube.list
    behavior: classical
    interval: 86400
    format: text
    type: http
rules:
  - "RULE-SET,Youtube,📹 YouTube"
  - "MATCH,🐟 漏网之鱼"
```
但是请求时判断为Match，导致使用的节点非我想指定的，但是奇怪的是该配置在IOS小火箭中运行正常

![Image](https://github.com/user-attachments/assets/29e11988-7228-43e3-9219-4f1024439653)
