### ISSUE TITLE
172开头的局域网IP走了代理,没有地方设置?

### ISSUE THREAD

**Issue by mrlbing** [chen08209/FlClash#340]
如题,172开头的局域网IP,默认走了代理,没找到地方设置.怎么办?只能一会儿关一会儿开?

**Comment by Carlos920** [comment]
最简单的方式是规则部分开头加上

```yaml
rules:
  - IP-CIDR,10.0.0.0/8,direct,no-resolve # A类私有网段
  - IP-CIDR,172.16.0.0/12,direct,no-resolve # B类私有网段
  - IP-CIDR,192.168.0.0/16,direct,no-resolve # C类私有网段
```

**Comment by likaifenkeng** [comment]
全局模式，局域网走代理。应该加个选项，私网地址是否走代理。

**Comment by mashirozx** [comment]
rule-provider 里面已经加上内网规则了，还是走了代理，配置摘要（[完整文件](https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Providers/LocalAreaNetwork.yaml)）：

```
payload:
  - IP-CIDR,192.168.0.0/16,no-resolve
```

但是 http://192.168.31.1/ 的流量还是走了代理


同样的 clash 配置文件在 clash meta for Android 和 clash verge 上都是能正常绕过此域名的

**Comment by mashirozx** [comment]
debug了一下，发现是 no-resolve 这样的写法报错了

![35b28f0e1d00620734ac74e7f58e8321](https://github.com/user-attachments/assets/b7d7caa1-b99d-497d-89c8-b1dbd7b73417)

**Comment by Carlos920** [comment]
> rule-provider 里面已经加上内网规则了，Android 上还是走了代理，rule-provider 摘要（[完整文件](https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Providers/LocalAreaNetwork.yaml)）：
> 
> ```yaml
> payload:
>   - IP-CIDR,192.168.0.0/16,no-resolve
> ```
> 
> clash 配置摘要
> ```yaml
> rule-providers:
>   LocalAreaNetwork: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml', path: ./ruleset/LocalAreaNetwork.yaml, interval: 86400 }
> 
> rules:
>   - 'RULE-SET,LocalAreaNetwork,DIRECT'
> ```
> 
> 但是 http://192.168.31.1/ 的流量还是走了代理
> 
> 
> 同样的 clash 配置文件在 clash meta for Android 和 clash verge 上都是能正常绕过此域名的

你规则写错了，是`- IP-CIDR,192.168.0.0/16,direct,no-resolve`

**Comment by mashirozx** [comment]
> > rule-provider 里面已经加上内网规则了，Android 上还是走了代理，rule-provider 摘要（[完整文件](https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Providers/LocalAreaNetwork.yaml)）：
> > ```yaml
> > payload:
> >   - IP-CIDR,192.168.0.0/16,no-resolve
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > clash 配置摘要
> > ```yaml
> > rule-providers:
> >   LocalAreaNetwork: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml', path: ./ruleset/LocalAreaNetwork.yaml, interval: 86400 }
> > 
> > rules:
> >   - 'RULE-SET,LocalAreaNetwork,DIRECT'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是 http://192.168.31.1/ 的流量还是走了代理
> > 同样的 clash 配置文件在 clash meta for Android 和 clash verge 上都是能正常绕过此域名的
> 
> 你规则写错了，是`- IP-CIDR,192.168.0.0/16,direct,no-resolve`

是的，但是这样的写法之前从旧版 clash 到 clash meta 都是支持的。这个已经确认是 mihomo 变动导致的问题，和这个项目无关。https://github.com/MetaCubeX/mihomo/issues/1532

**Comment by mashirozx** [comment]
嗯，理解错了，不过现在问题还是存在，rule-provider里面这样写，该ip段还是走了代理

```yaml
payload:
  - IP-CIDR,192.168.0.0/16,no-resolve
```

```yaml
rule-providers:
  LocalAreaNetwork: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml', path: ./ruleset/LocalAreaNetwork.yaml, interval: 86400 }

rules:
  - 'RULE-SET,LocalAreaNetwork,DIRECT'
```

**Comment by Carlos920** [comment]
> 嗯，理解错了，不过现在问题还是存在，rule-provider里面这样写，该ip段还是走了代理
> 
> ```yaml
> payload:
>   - IP-CIDR,192.168.0.0/16,no-resolve
> ```
> 
> ```yaml
> rule-providers:
>   LocalAreaNetwork: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml', path: ./ruleset/LocalAreaNetwork.yaml, interval: 86400 }
> 
> rules:
>   - 'RULE-SET,LocalAreaNetwork,DIRECT'
> ```
> 

如果你能保证这个是优于其他规则的就放rule-set里否则就放rules里的第一行

**Comment by mashirozx** [comment]
试了放到最前面也不行，打了一下log，发现似乎是此类 rule-provider 导致DNS server启动失败

```
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial configuration in progress, dateTime: 2024-09-22 13:05:14.941051}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Geodata Loader mode: memconservative, dateTime: 2024-09-22 13:05:14.943642}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Geosite Matcher implementation: succinct, dateTime: 2024-09-22 13:05:14.943974}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Initial configuration complete, total time: 2ms, dateTime: 2024-09-22 13:05:14.944351}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Sniffer is closed, dateTime: 2024-09-22 13:05:14.964627}
I/flutter (10611): Log{logLevel: LogLevel.error, payload: Start DNS server error: listen udp 0.0.0.0:53: bind: permission denied, dateTime: 2024-09-22 13:05:14.969038}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider BanEasyPrivacy, dateTime: 2024-09-22 13:05:14.986690}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider BanAD, dateTime: 2024-09-22 13:05:14.987087}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider LocalAreaNetwork, dateTime: 2024-09-22 13:05:14.987307}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider ChinaDomain, dateTime: 2024-09-22 13:05:14.987517}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider ChinaCompanyIp, dateTime: 2024-09-22 13:05:14.987728}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider ProxyGFWlist, dateTime: 2024-09-22 13:05:14.987948}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider UnBan, dateTime: 2024-09-22 13:05:14.988175}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider ChinaMedia, dateTime: 2024-09-22 13:05:14.988546}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,23.40.241.251/32,no-resolve], dateTime: 2024-09-22 13:05:14.988857}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,23.40.242.10/32,no-resolve], dateTime: 2024-09-22 13:05:14.989078}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,103.44.56.0/22,no-resolve], dateTime: 2024-09-22 13:05:14.989339}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,118.26.32.0/23,no-resolve], dateTime: 2024-09-22 13:05:14.989566}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,118.26.120.0/24,no-resolve], dateTime: 2024-09-22 13:05:14.989772}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,223.119.62.225/28,no-resolve], dateTime: 2024-09-22 13:05:14.990}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,106.11.0.0/16,no-resolve], dateTime: 2024-09-22 13:05:14.990246}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider BanEasyListChina, dateTime: 2024-09-22 13:05:15.079451}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider ChinaIpV6, dateTime: 2024-09-22 13:05:15.080257}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider ProtectIpLocation, dateTime: 2024-09-22 13:05:15.080841}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider ChinaIp, dateTime: 2024-09-22 13:05:15.081368}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider BanProgramAD, dateTime: 2024-09-22 13:05:15.081883}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider Download, dateTime: 2024-09-22 13:05:15.082310}
I/flutter (10611): Log{logLevel: LogLevel.info, payload: Start initial provider BanEasyList, dateTime: 2024-09-22 13:05:15.082835}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,0.0.0.0/8,no-resolve], dateTime: 2024-09-22 13:05:15.083355}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,139.220.243.27/32,no-resolve], dateTime: 2024-09-22 13:05:15.083821}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,172.16.102.56/32,no-resolve], dateTime: 2024-09-22 13:05:15.084107}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,185.188.32.1/28,no-resolve], dateTime: 2024-09-22 13:05:15.084325}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,221.226.128.146/32,no-resolve], dateTime: 2024-09-22 13:05:15.084515}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,2a0b:b580::/48,no-resolve], dateTime: 2024-09-22 13:05:15.084788}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,2a0b:b581::/48,no-resolve], dateTime: 2024-09-22 13:05:15.085009}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,2a0b:b582::/48,no-resolve], dateTime: 2024-09-22 13:05:15.085254}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,2a0b:b583::/48,no-resolve], dateTime: 2024-09-22 13:05:15.085496}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,1.12.12.12/32,no-resolve], dateTime: 2024-09-22 13:05:15.085718}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,10.0.0.0/8,no-resolve], dateTime: 2024-09-22 13:05:15.102719}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,100.64.0.0/10,no-resolve], dateTime: 2024-09-22 13:05:15.103154}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,127.0.0.0/8,no-resolve], dateTime: 2024-09-22 13:05:15.103424}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,172.16.0.0/12,no-resolve], dateTime: 2024-09-22 13:05:15.103724}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,192.168.0.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.104065}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,198.18.0.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.104285}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,224.0.0.0/4,no-resolve], dateTime: 2024-09-22 13:05:15.104513}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,::1/128,no-resolve], dateTime: 2024-09-22 13:05:15.104709}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,fc00::/7,no-resolve], dateTime: 2024-09-22 13:05:15.104914}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,fe80::/10,no-resolve], dateTime: 2024-09-22 13:05:15.105319}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,fd00::/8,no-resolve], dateTime: 2024-09-22 13:05:15.105573}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,13.32.0.0/15,no-resolve], dateTime: 2024-09-22 13:05:15.154975}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,13.35.0.0/17,no-resolve], dateTime: 2024-09-22 13:05:15.155486}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,18.184.0.0/15,no-resolve], dateTime: 2024-09-22 13:05:15.155734}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,18.194.0.0/15,no-resolve], dateTime: 2024-09-22 13:05:15.155912}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,18.208.0.0/13,no-resolve], dateTime: 2024-09-22 13:05:15.156121}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,18.232.0.0/14,no-resolve], dateTime: 2024-09-22 13:05:15.156339}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,52.58.0.0/15,no-resolve], dateTime: 2024-09-22 13:05:15.156512}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,52.74.0.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.156685}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,52.77.0.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.156903}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,52.84.0.0/15,no-resolve], dateTime: 2024-09-22 13:05:15.157131}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,52.200.0.0/13,no-resolve], dateTime: 2024-09-22 13:05:15.157311}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,54.93.0.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.157482}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,54.156.0.0/14,no-resolve], dateTime: 2024-09-22 13:05:15.157660}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,54.226.0.0/15,no-resolve], dateTime: 2024-09-22 13:05:15.157866}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,54.230.156.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.158060}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,31.13.24.0/21,no-resolve], dateTime: 2024-09-22 13:05:15.158331}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,31.13.64.0/18,no-resolve], dateTime: 2024-09-22 13:05:15.158612}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,45.64.40.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.158837}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,66.220.144.0/20,no-resolve], dateTime: 2024-09-22 13:05:15.159027}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,69.63.176.0/20,no-resolve], dateTime: 2024-09-22 13:05:15.159194}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,69.171.224.0/19,no-resolve], dateTime: 2024-09-22 13:05:15.159385}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,74.119.76.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.159561}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,103.4.96.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.159727}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,129.134.0.0/17,no-resolve], dateTime: 2024-09-22 13:05:15.159906}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,157.240.0.0/17,no-resolve], dateTime: 2024-09-22 13:05:15.160077}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,173.252.64.0/18,no-resolve], dateTime: 2024-09-22 13:05:15.160278}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,179.60.192.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.160497}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,185.60.216.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.160690}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,204.15.20.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.160866}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,74.125.0.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.161043}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,173.194.0.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.161218}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,120.232.181.162/32,no-resolve], dateTime: 2024-09-22 13:05:15.161430}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,120.241.147.226/32,no-resolve], dateTime: 2024-09-22 13:05:15.161665}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,120.253.253.226/32,no-resolve], dateTime: 2024-09-22 13:05:15.161847}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,120.253.255.162/32,no-resolve], dateTime: 2024-09-22 13:05:15.162026}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,120.253.255.34/32,no-resolve], dateTime: 2024-09-22 13:05:15.162285}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,120.253.255.98/32,no-resolve], dateTime: 2024-09-22 13:05:15.162497}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,180.163.150.162/32,no-resolve], dateTime: 2024-09-22 13:05:15.162666}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,180.163.150.34/32,no-resolve], dateTime: 2024-09-22 13:05:15.162844}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,180.163.151.162/32,no-resolve], dateTime: 2024-09-22 13:05:15.163061}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,180.163.151.34/32,no-resolve], dateTime: 2024-09-22 13:05:15.163231}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,203.208.39.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.163442}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,203.208.40.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.163696}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,203.208.41.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.163892}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,203.208.43.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.164102}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,203.208.50.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.164298}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,220.181.174.162/32,no-resolve], dateTime: 2024-09-22 13:05:15.164512}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,220.181.174.226/32,no-resolve], dateTime: 2024-09-22 13:05:15.164706}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,220.181.174.34/32,no-resolve], dateTime: 2024-09-22 13:05:15.164911}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,1.201.0.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.165090}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,27.0.236.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.165266}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,103.27.148.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.165387}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,103.246.56.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.165498}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,110.76.140.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.165607}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,113.61.104.0/22,no-resolve], dateTime: 2024-09-22 13:05:15.165715}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,103.2.28.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.165827}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,103.2.30.0/23,no-resolve], dateTime: 2024-09-22 13:05:15.165966}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,119.235.224.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.169712}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,119.235.232.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.169877}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,119.235.235.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.170006}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,119.235.236.0/23,no-resolve], dateTime: 2024-09-22 13:05:15.170156}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,147.92.128.0/17,no-resolve], dateTime: 2024-09-22 13:05:15.170278}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,203.104.128.0/19,no-resolve], dateTime: 2024-09-22 13:05:15.170391}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,91.108.0.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.170507}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,109.239.140.0/24,no-resolve], dateTime: 2024-09-22 13:05:15.170620}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,149.154.160.0/20,no-resolve], dateTime: 2024-09-22 13:05:15.171316}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,2001:67c:4e8::/48,no-resolve], dateTime: 2024-09-22 13:05:15.171431}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,2001:b28:f23d::/48,no-resolve], dateTime: 2024-09-22 13:05:15.171544}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR6,2001:b28:f23f::/48,no-resolve], dateTime: 2024-09-22 13:05:15.171656}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,18.194.0.0/15,no-resolve], dateTime: 2024-09-22 13:05:15.171767}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,34.224.0.0/12,no-resolve], dateTime: 2024-09-22 13:05:15.171877}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,54.242.0.0/15,no-resolve], dateTime: 2024-09-22 13:05:15.171987}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,50.22.198.204/30,no-resolve], dateTime: 2024-09-22 13:05:15.172113}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,208.43.122.128/27,no-resolve], dateTime: 2024-09-22 13:05:15.172226}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,108.168.174.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.172332}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,173.192.231.32/27,no-resolve], dateTime: 2024-09-22 13:05:15.172447}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,158.85.5.192/27,no-resolve], dateTime: 2024-09-22 13:05:15.172561}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,174.37.243.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.172676}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,158.85.46.128/27,no-resolve], dateTime: 2024-09-22 13:05:15.172791}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,173.192.222.160/27,no-resolve], dateTime: 2024-09-22 13:05:15.172904}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,184.173.128.0/17,no-resolve], dateTime: 2024-09-22 13:05:15.173015}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,158.85.224.160/27,no-resolve], dateTime: 2024-09-22 13:05:15.173132}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,75.126.150.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.173254}
I/flutter (10611): Log{logLevel: LogLevel.warning, payload: invalid domain:[IP-CIDR,69.171.235.0/16,no-resolve], dateTime: 2024-09-22 13:05:15.173369}
```

**Comment by mashirozx** [comment]
这是规则：

```yaml
rule-providers:
  BanAD: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanAD.yaml', path: ./ruleset/BanAD.yaml, interval: 86400 }
  BanEasyList: { type: http, behavior: classical, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyList.yaml', path: ./ruleset/BanEasyList.yaml, interval: 86400 }
  BanEasyListChina: { type: http, behavior: classical, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyListChina.yaml', path: ./ruleset/BanEasyListChina.yaml, interval: 86400 }
  BanEasyPrivacy: { type: http, behavior: classical, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyPrivacy.yaml', path: ./ruleset/BanEasyPrivacy.yaml, interval: 86400 }
  BanProgramAD: { type: http, behavior: classical, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanProgramAD.yaml', path: ./ruleset/BanProgramAD.yaml, interval: 86400 }
  ChinaDomain: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaDomain.yaml', path: ./ruleset/ChinaDomain.yaml, interval: 86400 }
  ChinaIp: { type: http, behavior: ipcidr, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaIp.yaml', path: ./ruleset/ChinaIp.yaml, interval: 86400 }
  ChinaIpV6: { type: http, behavior: classical, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaIpV6.yaml', path: ./ruleset/ChinaIpV6.yaml, interval: 86400 }
  ChinaCompanyIp: { type: http, behavior: ipcidr, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaCompanyIp.yaml', path: ./ruleset/ChinaCompanyIp.yaml, interval: 86400 }
  ChinaMedia: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaMedia.yaml', path: ./ruleset/ChinaMedia.yaml, interval: 86400 }
  Download: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Download.yaml', path: ./ruleset/Download.yaml, interval: 86400 }
  LocalAreaNetwork: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml', path: ./ruleset/LocalAreaNetwork.yaml, interval: 86400 }
  ProxyGFWlist: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyGFWlist.yaml', path: ./ruleset/ProxyGFWlist.yaml, interval: 86400 }
  UnBan: { type: http, behavior: domain, url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/UnBan.yaml', path: ./ruleset/UnBan.yaml, interval: 86400 }
```
