### ISSUE TITLE
rule-providers 中 type: file 的本地文件内容无法加载.

### ISSUE THREAD

**Issue by gsuns** [chen08209/FlClash#555]
FIClash版本 0.8.67

FIClash配置文件中的内容摘选:
```
rule-providers:
  # 域名 - 代理
  DomainProxy:
    type: file
    behavior: domain
    format: yaml
    path: /User/Rule/DomainProxy.yaml

rules:
  # 域名 - 代理
  - RULE-SET,DomainProxy,Proxy
  - MATCH,DIRECT
```
/User/Rule/DomainProxy.yaml 配置文件内容:
```
payload:
  - '+.google.com'
```

后来我不使用`- RULE-SET,DomainProxy,Proxy`,改成
```
  - DOMAIN-SUFFIX,google.com,Proxy
```
之后,可以正常访问.希望能够解决
