### ISSUE TITLE
希望出一个代理绕过指定网站或程序的功能

### ISSUE THREAD

**Issue by mcshangyun** [chen08209/FlClash#562]
有些时候访问一些国内网站，会出现无法访问等情况，并不想怎么去修改配置文件。
所以希望出一个类似Clash for Windows中system proxy bypass功能，代理绕过网站。

**Comment by paras-zomby** [comment]
你们说的这些功能不是可以用自建增强规则实现么，不过自建规则目前也是flclash上缺失的功能就是了

**Comment by gsuns** [comment]
请参考 https://wiki.metacubex.one/config/rules/
我自己测过了,FIClash可以根据 域名  或 Windows进程 或 IP,规则进行分流,根据规则觉得走代理还是直连

**Comment by gsuns** [comment]
另外说点我个人观点,如果你直接拿默认配置,或者别人的配置直接用,未必完全都适合自己.
所以....我个人时愿意花点时间,改改配置,这样可以一直爽下去.
我也是刚用FIClash没几天,最蛋疼的时不是改配置,而是找方法.一开始我连文档都找了很久 .
最后发现 https://wiki.metacubex.one/ 上,大部分配置都可以在FIClash上使用.
所以你是幸福的.

**Comment by gsuns** [comment]
下面是一个简单的规则示例,你可以参考下:
```
# 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
ipv6: true

proxies:
  #本地Socks5代理
  - name: LocalSocks5
    type: socks5
    server: 127.0.0.1
    port: 10010
    # username: username
    # password: password
    # tls: true
    # fingerprint: xxxx
    # skip-cert-verify: true
    # udp: true
    # ip-version: ipv6
   
dns:
  enable: true
#  prefer-h3: false
#  use-hosts: true
  use-system-hosts: true

  #dns 连接遵守路由规则，需配置 proxy-server-nameserver
  respect-rules: false
#  listen: 0.0.0.0:1053
  ipv6: true
# 使用本地自建DNS服务查询
  default-nameserver:
    - https://127.0.0.1:3000/dns-query
  enhanced-mode: redir-host
#  fake-ip-range: 198.18.0.1/16
#  fake-ip-filter-mode: blacklist
#  fake-ip-filter:
#    - '*.lan'
#  nameserver-policy:
#    '+.arpa': '10.0.0.1'
#    'rule-set:cn':
#    - https://doh.pub/dns-query
#    - https://dns.alidns.com/dns-query
  nameserver:
    - https://127.0.0.1:3000/dns-query

 # proxy-server-nameserver:
#    - https://doh.pub/dns-query
  direct-nameserver:
    - system
 # direct-nameserver-follow-policy: true
#  fallback:
#    - tls://8.8.4.4
#    - tls://1.1.1.1
#  fallback-filter:
#    geoip: true
#    geoip-code: CN
#    geosite:
#      - gfw
#    ipcidr:
#      - 240.0.0.0/4
#    domain:
#      - '+.google.com'
#      - '+.facebook.com'
#      - '+.youtube.com'
# 更改 geoip 使用文件，mmdb 或者 dat，可选 true/false,true为 dat，此项有默认值 false
geodata-mode: false

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - LocalSocks5

  # url-test 通过对 指定URL 进行基准速度测试来选择将使用哪个代理.
  - name: "Auto"
    type: url-test
    proxies:
      - LocalSocks5
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rules:
  # 私有地址 - 直连
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT

  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,169.254.0.0/16,DIRECT

  - GEOIP,CN,DIRECT
  

# 域名直连
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT


# 域名代理
 #  google.com 走代理
  - DOMAIN-SUFFIX,google.com,Proxy


# 应用代理
  #如果有QQ.EXE应用,走直连
  - PROCESS-NAME,QQ.exe,DIRECT
  #如果有firefox(火狐浏览器)应用,代理
  - PROCESS-NAME,sfirefox.exe,Proxy
 
 #如果上面规则都没有匹配到,最后走直连
  - MATCH,DIRECT
  ```
