### ISSUE TITLE
请问,自定 GEO,如何配置(不是在GUI上配置的这种方式)

### ISSUE THREAD

**Issue by gsuns** [chen08209/FlClash#565]
下面是我的配置
```
# 更改 geoip 使用文件，mmdb 或者 dat，可选 true/false,true为 dat，此项有默认值 false
geodata-mode: false

# 自动更新 GEO
geo-auto-update: false
# 更新间隔，单位为小时
geo-update-interval: 48

#自定义外部资源下载时使用的的 UA，默认为 clash.meta
global-ua: clash.meta

# 自定 GEO 下载地址
geox-url:
  geoip: https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
#  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb"
```
但似乎没有效果.
