### ISSUE TITLE
测速链接应该优先选择配置文件中每个代理组指定的测速链接

### ISSUE THREAD

**Issue by cesaryuan** [chen08209/FlClash#566]
在某些场景下，需要为不同的代理组使用不同的测速链接，因此我会将测速链接内嵌到配置中，如下所示：
```
  - name: Hide
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 600
    include-all: true
    exclude-filter: Mitm.*

  - name: 'Mitm'
    type: select
    url: http://api.bilibili.com
    interval: 600
    proxies:
      - 'Mitm Localhost'
      - 'Mitm Tailscale Minipc'
      - 'Mitm Tailscale Minipc Relay'
      - DIRECT
  ```
因此，希望FIClash可以优先选择配置文件中内嵌的测速链接进行测速，如果没有内嵌，则回退到应用中设置的测速链接
