### ISSUE TITLE
当节点过多时,点击测试, 只会测试很少一部分节点

### ISSUE THREAD

**Issue by lovitus** [chen08209/FlClash#644]
```yaml
  - name: 手动-全部订阅的全部节点除了特殊和俄罗斯-group
    use: 
      - A
      - AA
      - AAA
      - AAAA
      - AAAAA
      - ....
    type: select
    url: http://www.gstatic.com/generate_204
    interval: "1800"
    tolerance: "200"
    filter: '^(?!.*中国|.*俄罗斯|.*特殊|.*调试|.*异常).*$'
    lazy: true
```

这个测试组会有很多很多节点聚合, 但是点击测试时候, 只有1/3的节点能够进行测试,  剩下的节点永远不会测试.
是否:
- 分批测试时候, 忘记了处理剩下的数据?
