### ISSUE TITLE
[Question] 域名服务器策略如何填写多个候选？

### ISSUE THREAD

**Issue by sherlcok314159** [chen08209/FlClash#812]
请问域名服务器策略如何一个键对应多个值，比如：

```yaml
dns:
  nameserver-policy:
    # private 其实指的是 Reserved IP（保留地址），比如 192.168.0.0
    "geosite:cn,private":
      - https://223.5.5.5/dns-query # 阿里
      - https://120.53.53.53/dns-query # 腾讯
```

目前的软件是一个键对应一个值的形式，我试过输入 `dns1_link, dns2_link` 不行，直接拷贝上面的 yaml 也不行，或者是列表也不行
