### ISSUE TITLE
节点排序应始终将节点组置于最前

### ISSUE THREAD

**Issue by HDTianRu** [chen08209/FlClash#82]
如图，类似这种先将节点组按原顺序置于最前，再根据延迟对节点进行排序
![Screenshot](https://github.com/chen08209/FlClash/assets/103573273/904fe7d9-7a67-4096-af86-cbb3b2d7bf11)
以下为配置文件
```
p-proxies: &proxies
  - '🚀 节点选择'
  - '♻️ 自动选择(all)'
  - '♻️ 自动选择(赔钱)'
  - '♻️ 自动选择(CloudServer)'
  - DIRECT
  - REJECT

proxy-groups:
  - name: '🐟 漏网之鱼'
    type: select
    proxies: *proxies
    include-all-providers: true
```

**Comment by Voya9e** [comment]
没看懂，你能描述详细一点吗？

**Comment by HDTianRu** [comment]
在proxy-group中，可以添加proxy或其他proxy-group
在对其进行排序时，应先排序其他proxy-group，如上文中DIRECT，自动选择等
最后再排序proxy

**Comment by refined-fish** [comment]
> 在proxy-group中，可以添加proxy或其他proxy-group 在对其进行排序时，应先排序其他proxy-group，如上文中DIRECT，自动选择等 最后再排序proxy

这个完全是内核功能，与UI没有任何关联，请去mihomo提交（另外你说的真的好绕啊，我看了好几遍🤣）

**Comment by refined-fish** [comment]
> 在proxy-group中，可以添加proxy或其他proxy-group 在对其进行排序时，应先排序其他proxy-group，如上文中DIRECT，自动选择等 最后再排序proxy

而且理论上来说，这个顺序是根据你的yaml文件决定的，谁写在前面谁就在前面

**Comment by HDTianRu** [comment]
> > 在proxy-group中，可以添加proxy或其他proxy-group 在对其进行排序时，应先排序其他proxy-group，如上文中DIRECT，自动选择等 最后再排序proxy
> 
> 而且理论上来说，这个顺序是根据你的yaml文件决定的，谁写在前面谁就在前面

你可能没懂我的意思
同一份配置，像metacubexd UI就是先排proxy-groups再排proxies，分别按名字或延迟排序，而flclash就是总的混一起，再按名字或延迟排序
所以我希望flclash也能实现metacubexd UI这种分别排序行为
(另外因为我已经在用clash4magisk了，所以关掉issue)

**Comment by refined-fish** [comment]
> > > 在proxy-group中，可以添加proxy或其他proxy-group 在对其进行排序时，应先排序其他proxy-group，如上文中DIRECT，自动选择等 最后再排序proxy
> > 
> > 
> > 而且理论上来说，这个顺序是根据你的yaml文件决定的，谁写在前面谁就在前面
> 
> 你可能没懂我的意思 同一份配置，像metacubexd UI就是先排proxy-groups再排proxies，分别按名字或延迟排序，而flclash就是总的混一起，再按名字或延迟排序 所以我希望flclash也能实现metacubexd UI这种分别排序行为 (另外因为我已经在用clash4magisk了，所以关掉issue)

哦我懂你意思了，不好意思，按照你的yaml写法
```
proxy-groups:
  - name: '🐟 漏网之鱼'
    type: select
    proxies: *proxies
    include-all-providers: true
```
确实是`proxies: *proxies`在前，其他`include-all-providers: true`在后，面板的显示是完全正确的，我没有在Flclash用过这样的组合，所以没注意过问题，如果确有其事那可能是fl的显示逻辑是另外设计的，没有使用内核原本的样式（PS：不过我也是习惯直接用面板看hh）
