### ISSUE TITLE
Windows下tun模式更新订阅问题

### ISSUE THREAD

**Issue by memory9596** [chen08209/FlClash#971]
### 描述
订阅是用本地部署的Sub-Store进行管理的，网段为192.168.21.0/25。除tun模式以外，均能正常拉取订阅文件。类似的GUI客户端没有相同问题。

### 配置

```yaml
proxy-providers:
  provider1:
    url: ""
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204", interval: 300}

ipv6: true
allow-lan: true
mode: rule
mixed-port: 7890
external-controller: 0.0.0.0:9090

tcp-concurrent: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: false
  override-destination: false
  sniff:
    HTTP: {ports: [80,8080-8880]}
    TLS: {ports: [443,8443]}
    QUIC: {ports: [443,8443]}

tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53

dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  nameserver: [system,119.29.29.29]
  nameserver-policy:
    "geosite:gfw": [1.1.1.1,8.8.8.8]

proxies: []

proxy-groups:
  - name: Proxy
    type: select
    include-all: true
    proxies:
      - DIRECT

rules:
  - GEOSITE,cn,DIRECT
  - GEOSITE,gfw,Proxy
  - GEOIP,cn,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  - MATCH,Proxy
```

### 错误信息
```bash
DioException [bad response]: This exception was thrown because the response has a status code of 502 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 502 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
```

### 版本
- v0.8.78+3
